### PR TITLE
bump mmorph, update contact details in cabal file

### PR DESCRIPTION
**Pull request by andrewthad**

### CODE REVIEW

**Comment by ivan-m** [comment]
Why bump the lower bound on base?

And maybe add a changelog moving forward?

**Comment by andrewthad** [comment]
Yeah, I should definitely log this in a changelog. As far as dropping pre-AMP base, @treeowl had requested this. I suspect that it will allow us to weaken some `Monad` constraints to `Functor` (and replace `liftM` with `fmap`), but I haven't gone through and hunted down where those actually happen yet. David may have other things in mind though. Is it important for you that older `base` is supported?

**Comment by ivan-m** [comment]
I just didn't want it dropped for no reason :)

**Comment by sergv** [comment]
@andrewthad I think cabal file needs one more change in the `source-repository` section - it still contains old repository url in your branch.

**Comment by andrewthad** [comment]
@sergv Thanks! I had totally forgotten about that. I'm doing a bunch of error cleanup stuff right now, and I'll release 0.2.0.0 to hackage today.

**Pull request merged**
