### PR TITLE
Adjust for base 4.13 MonadFail changes

### PR DESCRIPTION
**Pull request by AndreasPK**

### CODE REVIEW

**Comment by chessai** [comment]
Thanks!

**Comment by chessai** [comment]
For some reason the merge on mobile is not working.

In the meantime could you add a changelog entry?

**Comment by AndreasPK** [comment]
I assume the way I added MonadFail is fine, but my concern was primarily the build no longer failing with GHC-HEAD.

It is probably worth adding the MonadFail instance unconditionally for backwards compatibility but then you might need to depend on the fail package for older versions and so on so I didn't look into this.

**Comment by andrewthad** [comment]
This looks correct to me. @AndreasPK Do you have any other concerns that you wanted to address before this is merged?

**Comment by AndreasPK** [comment]
From my end it's done :)

**Comment by AndreasPK** [comment]
Thanks should be fine as it is :)

Andrew Martin schrieb:

**Comment by hvr** [comment]
For the record: I've revised the recent release of streaming to account for its incompat with base-4.13 via  https://hackage.haskell.org/package/streaming-0.2.2.0/revisions/

**Comment by chessai** [comment]
Thanks @hvr!

**Comment by RyanGlScott** [comment]
Is it possible to make a new release of `streaming` with these changes?

**Comment by chessai** [comment]
yes.

**Comment by chessai** [comment]
uploaded at http://hackage.haskell.org/package/streaming-0.2.3.0. tag 0.2.3.0

**Comment by RyanGlScott** [comment]
Thanks!

**Pull request merged**
